# Generated by Django 4.1.3 on 2022-11-24 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='others', max_length=100)),
                ('description', models.TextField(default='TODO item')),
                ('created', models.DateField(default=datetime.datetime.now)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
